### ISSUE TITLE
Version error(Using default)

### ISSUE THREAD

**Issue by JunhoSer** [Fergui/m2m-api#2]
I want to receive true color images from usgs with m2m api. However, even though I entered my user name and password in the 'm2m=M2M()' part, the following error is displayed (I have even been issued a token).

>>> m2m = M2M()
Enter your username (or email): my name
Password: my password
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "D:\(Myname)\Lab\m2m\api.py", line 30, in __init__
    self.login(password)
  File "D:\(Myname)\Lab\m2m\api.py", line 72, in login
    self.apiKey = self.sendRequest('login',loginParameters)
  File "D:\(Myname)\Lab\m2m\api.py", line 56, in sendRequest
    raise M2MError(msg)
api.M2MError: 500 - VERSION_UNKNOWN - Unknown version used

Please help me solve this problem.

**Comment by Fergui** [comment]
The issue is authenticating in the M2M API site. 
Can you try logging into USGS [here](https://ers.cr.usgs.gov/) with the same username and password?

**Comment by matejkaj-cesnet** [comment]
Same issue here. I can login to site you mentioned wihtout any issues, but script returns `api.M2MError: 500 - VERSION_UNKNOWN - Unknown version used`.
Should I generate the login token? How can I use it in your script?
Thank you

**Comment by Fergui** [comment]
Thank you for your comment. Token login and token management are added to the last commit. Please try again using your token and let me know if the problem persists. Everything should work using prompts, so you should be able to run the code as before.

**Comment by matejkaj-cesnet** [comment]
Hello there, thank you for update. Unfortunately it did not resolve the issue.

I've tried to clean clone your repository and run it using new `main.py` script:
```
from api import M2M
if __name__ == '__main__':
    print('Hello world')
    m2m = M2M(username='username_im_using_for_usgs_login', token='newly_generated_token')
    print(m2m.permissions)
```
But the `api.M2MError: 500 - VERSION_UNKNOWN - Unknown version used` is still being raised when initializing the M2M class instance.

**Comment by matejkaj-cesnet** [comment]
Hello again, I've further analyzed the issue, and I think that I found the solution. 

### Changing API endpoint

The line 13 in file `api.py` must be changed from
```
M2M_ENDPOINT = 'https://m2m.cr.usgs.gov/api/api/json/{}'
```
to
```
M2M_ENDPOINT = 'https://m2m.cr.usgs.gov/api/api/json/{}/'
```
since the ending slash is not appended by specific endpoint in the script when calling the method `M2M.sendRequest()`.

### Correct username passing

Furthermore the method `M2M.authenticate()` must be updated as well on lines 43 and 44.

```
...
self.username = None
if username is None:
    ...
```
to
```
...
self.username = username
if self.username is None:
    ...
```

since for login the data of `self.username` is used and this variable is never assigned again if the `username` parameter of `M2M.authenticate()` is not None.

Hope you'll find my findings helpful.

**Comment by Fergui** [comment]
The first issue is odd because I am doing osp.join in line 81, which should join both parts of the URL accordingly (without needing the ending slash). But I can add it just in case (it never hurts).

For the second issue, you are right and the code was modified.

Thank you for your support and I hope the package is useful for you after all.

Angel Farguell

PS: I am working on a new release that will make the package downloadable using pip/conda install

**Comment by matejkaj-cesnet** [comment]
Thank you very much. I'm looking forward for the new release! Wish you all the best.
